apiVersion: v1
kind: Secret
metadata:
  name: paytrackr-secrets
  namespace: paytrackr
type: Opaque
stringData:
  # PostgreSQL credentials
  POSTGRES_USER: otto
  POSTGRES_PASSWORD: otto
  POSTGRES_DB: paytrackr
  # Connection string for the app
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=paytrackr;Username=otto;Password=otto"