apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paytrackr-monitor
  namespace: paytrackr
  labels:
    app: paytrackr
spec:
  selector:
    matchLabels:
      app: paytrackr
  endpoints:
  - port: http
    interval: 30s